name: axion
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  get: ^4.6.5
  google_fonts: ^6.2.1
  flutter_svg_provider: ^1.0.7
  lottie: ^3.3.0
  latlong2: ^0.9.0
  location: ^5.0.3
  shared_preferences: ^2.3.4
  rxdart: ^0.27.0
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_map_animations: ^0.8.0
  flutter_launcher_icons: "^0.14.2"
  fl_chart: ^0.70.1
  permission_handler: ^11.3.1
  flutter_foreground_task: ^8.17.0
  url_launcher: ^6.1.8
  battery_plus: ^6.2.1
  disable_battery_optimization: ^1.1.1
  package_info_plus: ^8.2.1
  #firebase
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  haversine_distance: ^1.2.1
  flutter_svg: ^2.0.17

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_version: 21
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/svg/

  fonts:
    - family: l
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        # - asset: assets/fonts/Roboto-Bold.ttf
        # weight: 700

    - family: p
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        # - asset: assets/fonts/Roboto-Bold.ttf
        # weight: 700
